# Generated by Django 3.2 on 2021-04-27 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('what_needs_to_get_done', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Topic',
            new_name='Task',
        ),
    ]
