# Generated by Django 3.2 on 2021-04-27 17:41

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('what_needs_to_get_done', '0002_rename_topic_task'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='task',
            managers=[
                ('task', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='task',
            name='text',
            field=models.TextField(),
        ),
    ]
