# Generated by Django 3.2 on 2021-04-27 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('what_needs_to_get_done', '0004_auto_20210427_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='status',
            field=models.TextField(choices=[('C', 'Completed'), ('I', 'In progress'), ('N', 'Not started'), ('O', 'Overdue')], default='N', max_length=1),
        ),
    ]
