# Generated by Django 3.2 on 2021-04-27 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('what_needs_to_get_done', '0006_alter_duedate_date_due'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='task',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='text',
            new_name='title',
        ),
        migrations.AddField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.TextField(choices=[('Completed', 'Completed'), ('In progress', 'In progress'), ('Not started', 'Not started'), ('Overdue', 'Overdue')], default='Not started'),
        ),
        migrations.DeleteModel(
            name='DueDate',
        ),
        migrations.DeleteModel(
            name='Status',
        ),
    ]
