# Generated by Django 3.2 on 2021-04-29 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('what_needs_to_get_done', '0007_auto_20210427_1952'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-due_date']},
        ),
    ]
